# Meta Data for SEO

## Homepage
title = "NRCHKB"
titleSeparator = "-"
titleAddition = "HomeKit all the things!"
description = "NRCHKB is a Node-RED nodes pack to simulate Apple HomeKit devices. The goal is to emulate native HomeKit devices as closely as possible."

## Open Graph + Twitter Cards
images = ["images/social-preview.png"]
#twitterSite = ""
#twitterCreator = ""
#facebookAuthor = ""
#facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "images/logo.png"
#schemaTwitter = ""
#schemaLinkedIn = ""
schemaGitHub = "https://github.com/NRCHKB"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#8f0000"

# Images
quality = 100
bgColor = "#8f0000"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like NRCHKB? <a class=\"alert-link\" href=\"https://github.com/NRCHKB/node-red-contrib-homekit-bridged\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/NRCHKB/NRCHKB.github.io"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
