[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --environment netlify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "netlify"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --environment netlify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "netlify"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
