on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for linting errors
        run: yarn test

      - name: Update metadata
        shell: 'script --return --quiet --command "bash {0}"' # used to run with TTY
        run: yarn update:metadata

      - name: Push updated metadata
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          disable_globbing: true
          commit_message: 'updated metadata'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          file_pattern: |
            content/*.md
            data/nrchkb/contributors.json

      - name: Build production website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
